export enum SocketMessageType {
    STIMULATOR_CONNECTION_STATE,
    IPC_CONNECTION_STATE,

    CLIENT_READY,

    EXPERIMENT_TOGGLE_SYNCHRONIZATION,

    STIMULATOR_DATA_STATE,

    EXPERIMENT_RESULT_CREATED,

    EXPERIMENT_PLAYER_DATA_IO,
    EXPERIMENT_PLAYER_STATE,

    ASSET_PLAYER_SYNCHRONIZATION,

    SETTINGS_UPDATE
}
