export enum SocketMessageSpecialization {
    CLIENT,
    EXPERIMENTS,
    EXPERIMENT_RESULTS,
    SEQUENCES,
    CONNECTION,
    STIMULATOR,
    EXPERIMENT_PLAYER,
    SERIAL_PORT,
    SETTINGS,
    FILE_BROWSER,
    ASSET_PLAYER
}
